name: ssd_barre_new # IMPORTANT: Update the name to match your new project name
description: "A new Flutter project for SSD Barre."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.1.4
  firebase_messaging: ^15.0.0
  cloud_functions: ^5.0.0
  rxdart: ^0.27.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  firebase_storage: ^12.1.0
  intl: ^0.19.0
  url_launcher: ^6.3.0 # NEW: Added url_launcher dependency
  firebase_app_check: ^0.3.2+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutterfire_cli: ^1.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/ssd_logo.jpeg
    - assets/app_icon.png
    - assets/splash_screen.jpg

  fonts:
    - family: SSDHeader
      fonts:
        - asset: assets/fonts/ssd_1.otf
    - family: SSDBody
      fonts:
        - asset: assets/fonts/ssd_2.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 23
  adaptive_icon_background: "#D13034"
