    // File generated by FlutterFire CLI.
    // For more information, see: https://firebase.google.com/docs/cli/#flutter_options
    import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
    import 'package:flutter/foundation.dart'
        show defaultTargetPlatform, TargetPlatform, kIsWeb; // Added kIsWeb

    // Default FirebaseOptions for all platforms.
    // YOU MUST REPLACE THE PLACEHOLDER VALUES BELOW WITH YOUR ACTUAL VALUES FROM FIREBASE CONSOLE
    // DO NOT COMMIT THIS FILE WITH SENSITIVE INFORMATION IF IT'S NOT MEANT TO BE PUBLIC
    class DefaultFirebaseOptions {
      static FirebaseOptions get currentPlatform {
        if (kIsWeb) { // Use kIsWeb for web platform check
          return const FirebaseOptions(
            apiKey: 'AIzaSyCsfkob-1eFA9Zl0LgxQc64TVaAty67UVo',
            appId: 'YOUR_WEB_APP_ID', // Replace with your Web App ID once you add a Web app in Firebase
            messagingSenderId: '706302299278',
            projectId: 'ssdbarreapp',
            storageBucket: 'ssdbarreapp.appspot.com',
          );
        }
        switch (defaultTargetPlatform) {
          case TargetPlatform.android:
            return const FirebaseOptions(
              apiKey: 'AIzaSyCsfkob-1eFA9Zl0LgxQc64TVaAty67UVo', // From Firebase Console -> Project settings -> Web API Key
              appId: '1:706302299278:android:c8fc078cb113fd0ad88ddf', // Updated with your specific Android App ID
              messagingSenderId: '706302299278', // From Firebase Console -> Project settings -> Cloud Messaging tab (Project Number)
              projectId: 'ssdbarreapp', // From Firebase Console -> Project settings -> General tab
              storageBucket: 'ssdbarreapp.appspot.com', // From Firebase Console -> Project settings -> Storage tab
            );
          case TargetPlatform.iOS:
            return const FirebaseOptions(
              apiKey: 'AIzaSyCsfkob-1eFA9Zl0LgxQc64TVaAty67UVo',
              appId: 'YOUR_IOS_APP_ID', // Replace with your iOS App ID once you add an iOS app in Firebase
              messagingSenderId: '706302299278',
              projectId: 'ssdbarreapp',
              storageBucket: 'ssdbarreapp.appspot.com',
              // Add bundleId if you plan to use iOS
              // bundleId: 'com.example.ssdBarreFixed', // Your iOS Bundle ID
            );
          case TargetPlatform.macOS:
            return const FirebaseOptions(
              apiKey: 'AIzaSyCsfkob-1eFA9Zl0LgxQc64TVaAty67UVo',
              appId: 'YOUR_MACOS_APP_ID', // Replace with your macOS App ID once you add a macOS app in Firebase
              messagingSenderId: '706302299278',
              projectId: 'ssdbarreapp',
              storageBucket: 'ssdbarreapp.appspot.com',
              // Add bundleId if you plan to use macOS
              // bundleId: 'com.example.ssdBarreFixed', // Your macOS Bundle ID
            );
          case TargetPlatform.windows:
            return const FirebaseOptions(
              apiKey: 'AIzaSyCsfkob-1eFA9Zl0LgxQc64TVaAty67UVo',
              appId: 'YOUR_WINDOWS_APP_ID', // Replace with your Windows App ID once you add a Windows app in Firebase
              messagingSenderId: '706302299278',
              projectId: 'ssdbarreapp',
              storageBucket: 'ssdbarreapp.appspot.com',
            );
          default:
            throw UnsupportedError(
              'DefaultFirebaseOptions are not supported for this platform.',
            );
        }
      }
    }
